### PR TITLE
37 reporting

### PR DESCRIPTION
**Pull request by J-J-B-J**
This PR adds feature #37 

I have done this by creating a new `Report` object, based on the `Attachment` object but with a `Date` attribute. There is a new attribute of the `User` object, called `reports`, which is a list of reports.

### CODE REVIEW

**Comment by J-J-B-J** [comment]
@SuperHarmony910 Please Review

**Comment by SuperHarmony910** [comment]
oh ye sure gimme a min

**Comment by J-J-B-J** [comment]
Thanks. If you have time, could you also do the other 2 please?

**Comment by SuperHarmony910** [comment]
oh shoot sorry i didn't check- sure i'll do the other 2

**Comment by J-J-B-J** [comment]
No problem! Thanks!

**Comment by SuperHarmony910** [comment]
um so i've tried to check the report function but it doesn't rlly show up in the gui? and i'm kinda not sure how to navigate thru this so ya- is it bcs maybe today's a sunday and it can't fetch the journal, which also for some reason might disallow report viewing?

**Comment by J-J-B-J** [comment]
True dat. I'll have a look

**Comment by J-J-B-J** [comment]
OK fixed it

**Comment by J-J-B-J** [comment]
I think

**Comment by SuperHarmony910** [comment]
oki time to check

**Comment by SuperHarmony910** [comment]
noice it works, i'll approve now !

**Review by SuperHarmony910 — APPROVED** [review]
poggies

**Pull request merged**
