### PR TITLE
Journal

### PR DESCRIPTION
**Pull request by J-J-B-J**
This PR adds feature #18 

I have done this by adding to the existing user sctaping function and objects, then building this into the app's "me" section.

### CODE REVIEW

**Review by SuperHarmony910 — COMMENTED** [review]
poggies

**Comment by J-J-B-J** [comment]
so good or bad?

**Review by SuperHarmony910 — APPROVED** [review]
yep it seems to work fine! on an unrelated sidenote, check out #21 ?

**Comment by SuperHarmony910** [comment]
yep it seems to work fine! on an unrelated sidenote, check out #21 ?

**Comment by SuperHarmony910** [comment]
uh oh apparently you can't merge since not all commits are signed- i can try help you with gpg keys next monday possibly but uh for now you should disable that and then we can re-enable it later once your commit signature verification software is set up

**Pull request merged**
