### PR TITLE
15 attachments for daily notices

### PR DESCRIPTION
**Pull request by J-J-B-J**
This PR adds feature #15 

I have done this by updating the `scrape_notices()` function to include attachments, and adding a new object called `Attachment` to `objects.py`. The `Attachment` object has two properties: `name` and `url`. `name` is the file name, and `url` is the website it can be found at.

### CODE REVIEW

**Comment by SuperHarmony910** [comment]
welp isn't it annoying making a whole feature and then not being able to test it-

**Review by SH910 — APPROVED** [review]

**Review by SuperHarmony910 — APPROVED** [review]
W

**Comment by J-J-B-J** [comment]
Nobody cares if you approve, @SH910. We only care about @SuperHarmony910's opinion.

**Comment by J-J-B-J** [comment]
For those of you who are wondering why I am being so rude, @SH910 is @SuperHarmony910's @education email

**Pull request merged**
