### PR TITLE
Added 'journal unavailable' error if journal input on dashboard cannot be found

### PR DESCRIPTION
**Pull request by SuperHarmony910**
This PR fixes issue #35 

I have done this by first checking if `bs4` can find and initialise the variable `journal_form` (`scrapers.py`) with the form used on the Sentral dashboard to post students' journals. If the form is unavailable, the try-except implemented will set the variable `journal` to `ERR_JOURNAL_UNAVAILABLE`. Then, when the Tkinter frames and text box are initialised, the program checks if the `journal` variable contains the error. If it does, it will disable the textbox and the submit button, and replace the text in the textbox with an error telling the user that the journal cannot be used right now, presumably because it is a holiday or weekend.

Referring to something mentioned in #35 , I didn't know how to initialise a variable part of the `SentralTimetable` object to make `SentralTimetable.JOURNAL_UNAVAILABLE`, so if @J-J-B-J you could help make it an error part of the object instead of a string error, that would be greatly appreciated :)

### CODE REVIEW

**Comment by SuperHarmony910** [comment]
i've just realised u manage PRs with 'rebase and merge'... which means you've probably committed a lot more than u might've originally thought since it just adds up all ur commits from the PR into one commit

**Comment by J-J-B-J** [comment]
> i've just realised u manage PRs with 'rebase and merge'... which means you've probably committed a lot more than u might've originally thought since it just adds up all ur commits from the PR into one commit

Yes. There are other ways available but I like this the most, as users can't accidentally download a faulty version of the software.

**Comment by SuperHarmony910** [comment]
> > i've just realised u manage PRs with 'rebase and merge'... which means you've probably committed a lot more than u might've originally thought since it just adds up all ur commits from the PR into one commit
> 
> Yes. There are other ways available but I like this the most, as users can't accidentally download a faulty version of the software.

ohh okay- soo uh what do you think of this?

**Comment by J-J-B-J** [comment]
I'm currently adjusting it so that it returns `get_timetable().user.journal` as a custom `JournalUnavailableError(Exception)` object. Just taking a while to figure it out. Should be done sometime tonight or tomorrow morning.

**Comment by J-J-B-J** [comment]
OK. That commit changed the error from a `<str>` to a `<type>` (more commonly known as a CLASS, thank you very much python!!!) Looks good to me. I'll leave the merging to you.

**Review by J-J-B-J — APPROVED** [review]
Looks good to me!

**Comment by SuperHarmony910** [comment]
> OK. That commit changed the error from a `<str>` to a `<type>` (more commonly known as a CLASS, thank you very much python!!!) Looks good to me. I'll leave the merging to you.

tysm ! sorry about my incompetency to tackle such a simple problem, i haven't worked in python in a bit 😅

**Comment by J-J-B-J** [comment]
> > OK. That commit changed the error from a `<str>` to a `<type>` (more commonly known as a CLASS, thank you very much python!!!) Looks good to me. I'll leave the merging to you.
> 
> tysm ! sorry about my incompetency to tackle such a simple problem, i haven't worked in python in a bit 😅

No problemo.

**Pull request merged**
